baseURL = "https://rmitlibrary.github.io/skills-for-nd-students/"
locale = "en-AU"
title = "Skills for neurodivergent students"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
# Disable default taxonomies

[outputs]
home = ["HTML", "RSS", "Robots"]